on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Run "npm run build"
        run: |
          npm install
          npm run build

      - name: Authenticate to AWS using GitHub OIDC (GHARole)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::621716744482:role/GHARole
          aws-region: us-east-1

      - name: S3 Sync
        run: |
          # the active command attempts to preserve the yan folder in the bucket, which is not part of the repo
          # append --dryrun to for testing purposes
          aws s3 sync ./dist s3://gabrielwelvaert.com-621716744482-us-east-1-an --delete --exclude "yan/*" --exclude "yan" --dryrun
          # this commented out variation does not attempt to preserve the yan folder in the bucket, , which is not part of the repo
          # aws s3 sync ./dist s3://gabrielwelvaert.com-621716744482-us-east-1-an --delete
      
      - name: Cloudfront invalidation
        run:
          aws cloudfront create-invalidation --distribution-id E2N25ZYA36C2IY --paths "/*"